### PR TITLE
Use win_service module instead of win_shell

### PR DESCRIPTION
**Pull request by nre-ableton**
- Use win_service module instead of win_shell
- Version 0.0.3

### CODE REVIEW

**Review by rco-ableton — APPROVED** [review]
LGTM 👍

**Comment by nre-ableton** [comment]
This doesn't work, see https://github.com/ansible-collections/community.windows/issues/290.

**Comment by nre-ableton** [comment]
...on second thought, it might work. See https://github.com/ansible-collections/community.windows/issues/290#issuecomment-915185983. I'm running an integration test now.

**Comment by nre-ableton** [comment]
@ablbot autosqash

**Comment by nre-ableton** [comment]
@ablbot autosquash

**Comment by nre-ableton** [comment]
So yes, it turns out that this will work! Mind taking another look @rco-ableton?

**Review by rco-ableton — APPROVED** [review]
Still LGTM 👍

**Pull request merged**
